// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_multinom_fit_cpp
List fast_multinom_fit_cpp(const arma::mat& X, const arma::mat& Y, const arma::vec& w, int max_iter, double tol, double ridge, int nthreads, Rcpp::Nullable<Rcpp::NumericMatrix> B_init, double eta_clip);
RcppExport SEXP _flexmix_extensions_fast_multinom_fit_cpp(SEXP XSEXP, SEXP YSEXP, SEXP wSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP ridgeSEXP, SEXP nthreadsSEXP, SEXP B_initSEXP, SEXP eta_clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< double >::type eta_clip(eta_clipSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_multinom_fit_cpp(X, Y, w, max_iter, tol, ridge, nthreads, B_init, eta_clip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flexmix_extensions_fast_multinom_fit_cpp", (DL_FUNC) &_flexmix_extensions_fast_multinom_fit_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_flexmix_extensions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
