# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_multinom_fit_cpp <- function(X, Y, w, max_iter = 100L, tol = 1e-8, ridge = 1e-6, nthreads = 0L, B_init = NULL, eta_clip = 30.0) {
    .Call('_flexmix_extensions_fast_multinom_fit_cpp', PACKAGE = 'flexmix.extensions', X, Y, w, max_iter, tol, ridge, nthreads, B_init, eta_clip)
}

